// Ujjivan Small Finance Bank — Technical Report Template V1
// All field configs, section definitions, mandatory fields & photo categories

export const UJJIVAN_TEMPLATE_V1 = {
  bank: 'UJJ',
  bankName: 'Ujjivan Small Finance Bank',
  templateId: 'ujjivan-technical-v1',
  templateName: 'Ujjivan Technical Report V1',
  version: 1,
  reportFormat: 'xlsx',

  sections: [
    {
      id: 'caseInfo',
      title: 'Case Information',
      icon: '📋',
      fields: [
        { key: 'refNo', label: 'Reference Number', type: 'text', required: true },
        { key: 'reportDate', label: 'Report Date', type: 'date', required: true },
        { key: 'dateOfInspection', label: 'Date of Inspection', type: 'date', required: true },
        { key: 'caseType', label: 'Type of Case', type: 'select', options: ['LAP','Home Loan','Business Loan','OD','NRP','Others'], required: true },
        { key: 'purposeOfValuation', label: 'Purpose of Valuation', type: 'select', options: ['Home Loan','LAP','OD','Resale','Others'], required: true },
        { key: 'valuerName', label: 'Valuer Name', type: 'text', required: true },
        { key: 'valuerContact', label: 'Valuer Contact Number', type: 'phone' },
        { key: 'branchName', label: 'Branch', type: 'text', required: true },
        { key: 'contactedPerson', label: 'Person Contacted During Inspection', type: 'text', required: true },
        { key: 'contactPersonMobile', label: 'Contact Person Mobile', type: 'phone' },
        { key: 'place', label: 'Place', type: 'text' },
        { key: 'distanceFromCity', label: 'Distance From City Centre', type: 'text' },
        { key: 'nearestLandmark', label: 'Nearest Landmark', type: 'text' },
      ],
    },
    {
      id: 'applicant',
      title: 'Applicant Details',
      icon: '👤',
      fields: [
        { key: 'applicantName', label: 'Applicant Name', type: 'text', required: true },
        { key: 'coApplicantName', label: 'Co-Applicant Name', type: 'text' },
        { key: 'customerId', label: 'Customer ID', type: 'text' },
        { key: 'clientId', label: 'Client ID', type: 'text' },
        { key: 'applicantContact', label: 'Applicant Contact Number', type: 'phone' },
        { key: 'ownerName', label: 'Owner Name', type: 'text', required: true },
        { key: 'propertyOwnerName', label: 'Property Owner Name', type: 'text' },
        { key: 'ownerContact', label: 'Owner Contact Number', type: 'phone' },
        { key: 'relationshipWithApplicant', label: 'Relationship With Applicant', type: 'select', options: ['Self','Applicant','Spouse','Parent','Sibling','Other'] },
        { key: 'vipCategory', label: 'VIP / VVIP', type: 'boolean' },
        { key: 'customerCategory', label: 'Customer Category', type: 'select', options: ['Normal','VIP','VVIP'] },
      ],
    },
    {
      id: 'propertyIdentification',
      title: 'Property Identification',
      icon: '🏠',
      fields: [
        { key: 'propertyType', label: 'Property Type', type: 'select', required: true, options: ['Vacant Site','Residential','Commercial','Industrial','Apartment','Villa','Agricultural','Mixed Use','Other'] },
        { key: 'propertySubType', label: 'Property Sub-Type', type: 'text' },
        { key: 'currentUsage', label: 'Current Usage', type: 'text', required: true },
        { key: 'permittedUsage', label: 'Permitted Usage', type: 'text' },
        { key: 'approvedUsage', label: 'Approved Usage', type: 'text' },
        { key: 'surveyNumber', label: 'Survey Number', type: 'text', required: true },
        { key: 'oldSurveyNumber', label: 'Old Survey Number', type: 'text' },
        { key: 'newSurveyNumber', label: 'New Survey Number', type: 'text' },
        { key: 'plotNumber', label: 'Plot Number', type: 'text' },
        { key: 'doorNumber', label: 'Door Number', type: 'text' },
        { key: 'propertyNumber', label: 'Property Number', type: 'text' },
        { key: 'village', label: 'Village', type: 'text' },
        { key: 'panchayat', label: 'Panchayat', type: 'text' },
        { key: 'union', label: 'Union', type: 'text' },
        { key: 'taluk', label: 'Taluk', type: 'text', required: true },
        { key: 'district', label: 'District', type: 'text', required: true },
        { key: 'state', label: 'State', type: 'text', required: true },
        { key: 'pincode', label: 'Pincode', type: 'text' },
        { key: 'jurisdiction', label: 'Jurisdiction', type: 'text' },
        { key: 'zonalClassification', label: 'Zonal Classification', type: 'text' },
        { key: 'identificationMethod', label: 'Property Identification Method', type: 'text' },
        { key: 'propertyIdentified', label: 'Property Identified', type: 'boolean', required: true },
        { key: 'propertyDemarcated', label: 'Property Demarcated', type: 'boolean' },
      ],
    },
    {
      id: 'addressDocument',
      title: 'Address As Per Document',
      icon: '📄',
      fields: [
        { key: 'docAddrDoorNo', label: 'Door / Plot Number', type: 'text' },
        { key: 'docAddrSurveyNo', label: 'Survey Number', type: 'text' },
        { key: 'docAddrStreet', label: 'Street', type: 'text' },
        { key: 'docAddrVillage', label: 'Village', type: 'text' },
        { key: 'docAddrTaluk', label: 'Taluk', type: 'text' },
        { key: 'docAddrDistrict', label: 'District', type: 'text' },
        { key: 'docAddrState', label: 'State', type: 'text' },
        { key: 'docAddrPincode', label: 'Pincode', type: 'text' },
        { key: 'documentAddress', label: 'Full Document Address', type: 'textarea' },
      ],
    },
    {
      id: 'addressSite',
      title: 'Address As At Site',
      icon: '📍',
      fields: [
        { key: 'siteAddrSameAsDoc', label: 'Address Same As Document', type: 'boolean' },
        { key: 'siteAddrDoorNo', label: 'Door / Plot Number', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddrSurveyNo', label: 'Survey Number', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddrStreet', label: 'Street', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddrVillage', label: 'Village', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddrTaluk', label: 'Taluk', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddrDistrict', label: 'District', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddrState', label: 'State', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddrPincode', label: 'Pincode', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddress', label: 'Full Site Address', type: 'textarea', required: true },
      ],
    },
    {
      id: 'locationAccess',
      title: 'Location & Access',
      icon: '🛣️',
      fields: [
        { key: 'roadName', label: 'Road Name', type: 'text' },
        { key: 'accessRoadType', label: 'Access Road Type', type: 'select', options: ['National Highway','State Highway','District Road','Panchayat Road','Private Road','Other'] },
        { key: 'approachRoadCondition', label: 'Approach Road Condition', type: 'select', options: ['Good','Average','Poor'] },
        { key: 'approachRoadWidth', label: 'Approach Road Width', type: 'text' },
        { key: 'roadWidth', label: 'Road Width', type: 'text' },
        { key: 'accessDetails', label: 'Access Details', type: 'textarea' },
        { key: 'distanceFromBranch', label: 'Distance From Branch (km)', type: 'text', required: true },
        { key: 'railwayStation', label: 'Railway Station', type: 'text' },
        { key: 'railwayStationDistance', label: 'Railway Station Distance', type: 'text' },
        { key: 'busStop', label: 'Bus Stop', type: 'text' },
        { key: 'busStopDistance', label: 'Bus Stop Distance', type: 'text' },
        { key: 'nearbyAmenities', label: 'Nearby Civic Amenities', type: 'textarea' },
        { key: 'publicTransport', label: 'Public Transport Availability', type: 'select', options: ['Available','Limited','Not Available'] },
        { key: 'surroundingLocality', label: 'Surrounding Locality', type: 'textarea' },
      ],
    },
    {
      id: 'locality',
      title: 'Locality Details',
      icon: '🏘️',
      fields: [
        { key: 'classOfLocality', label: 'Class of Locality', type: 'select', options: ['Posh','MIG','Middle Class','Low Class','Other'] },
        { key: 'siteDevelopment', label: 'Site Development', type: 'select', options: ['Developed','Developing','Under Development','Slow Developing'] },
        { key: 'marketability', label: 'Marketability', type: 'select', options: ['Excellent','Very Good','Good','Average','Poor'] },
        { key: 'surroundingHabitation', label: 'Surrounding Habitation (%)', type: 'number' },
        { key: 'surroundingDevelopment', label: 'Surrounding Development', type: 'textarea' },
        { key: 'localityDescription', label: 'Locality Description', type: 'textarea' },
        { key: 'proximityToAmenities', label: 'Proximity to Civic Amenities', type: 'textarea' },
      ],
    },
    {
      id: 'plotSite',
      title: 'Plot / Site Details',
      icon: '📐',
      fields: [
        { key: 'plotShape', label: 'Plot Shape', type: 'select', options: ['Regular','Irregular','Square','Rectangular','Triangular','L-Shape','Other'] },
        { key: 'siteAreaDoc', label: 'Site Area As Per Document', type: 'text' },
        { key: 'siteAreaPatta', label: 'Site Area As Per Patta', type: 'text' },
        { key: 'siteAreaPlan', label: 'Site Area As Per Plan', type: 'text' },
        { key: 'siteAreaActual', label: 'Site Area As At Site (Actual)', type: 'text', required: true },
        { key: 'plotArea', label: 'Plot Area', type: 'text', required: true },
        { key: 'landArea', label: 'Land Area', type: 'text' },
        { key: 'udsArea', label: 'UDS Area', type: 'text' },
        { key: 'areaUnit', label: 'Area Unit', type: 'select', options: ['Sq.Ft','Sq.M','Sq.Yard','Acre','Cent','Ground','Other'] },
        { key: 'areaForValuation', label: 'Area Considered For Valuation', type: 'text', required: true },
        { key: 'lengthDimension', label: 'Length', type: 'text' },
        { key: 'widthDimension', label: 'Width', type: 'text' },
        { key: 'northDimension', label: 'North Dimension', type: 'text' },
        { key: 'southDimension', label: 'South Dimension', type: 'text' },
        { key: 'eastDimension', label: 'East Dimension', type: 'text' },
        { key: 'westDimension', label: 'West Dimension', type: 'text' },
      ],
    },
    {
      id: 'boundaries',
      title: 'Boundary Details',
      icon: '🧭',
      fields: [
        { key: 'northBoundaryDoc', label: 'North — As Per Document', type: 'text', required: true },
        { key: 'northBoundarySite', label: 'North — As At Site', type: 'text', required: true },
        { key: 'southBoundaryDoc', label: 'South — As Per Document', type: 'text', required: true },
        { key: 'southBoundarySite', label: 'South — As At Site', type: 'text', required: true },
        { key: 'eastBoundaryDoc', label: 'East — As Per Document', type: 'text', required: true },
        { key: 'eastBoundarySite', label: 'East — As At Site', type: 'text', required: true },
        { key: 'westBoundaryDoc', label: 'West — As Per Document', type: 'text', required: true },
        { key: 'westBoundarySite', label: 'West — As At Site', type: 'text', required: true },
        { key: 'boundariesMatching', label: 'Boundaries Matching', type: 'boolean', required: true },
        { key: 'boundaryDifferenceRemarks', label: 'Boundary Difference Remarks', type: 'textarea', showIf: { field: 'boundariesMatching', value: false } },
      ],
    },
    {
      id: 'occupancy',
      title: 'Occupancy',
      icon: '🔑',
      fields: [
        { key: 'presentOccupancy', label: 'Present Occupancy', type: 'select', required: true, options: ['Self Occupied','Tenant Occupied','Vacant','Partially Occupied','Under Construction','Other'] },
        { key: 'occupantName', label: 'Occupant Name', type: 'text' },
        { key: 'occupantRelationship', label: 'Relationship With Applicant', type: 'select', options: ['Self','Applicant','Spouse','Parent','Sibling','Tenant','Other'] },
        { key: 'occupancyCurrentUsage', label: 'Current Usage', type: 'text' },
        { key: 'usageVerified', label: 'Usage Verified', type: 'boolean' },
      ],
    },
    {
      id: 'building',
      title: 'Building / Structure Details',
      icon: '🏗️',
      showIf: { field: 'propertyType', notIn: ['Vacant Site','Agricultural'] },
      fields: [
        { key: 'typeOfStructure', label: 'Type of Structure', type: 'select', options: ['RCC','Load Bearing','Steel','Timber','Brick','Other'] },
        { key: 'typeOfConstruction', label: 'Type of Construction', type: 'select', options: ['Framed','Load Bearing','Composite','Other'] },
        { key: 'foundation', label: 'Foundation', type: 'select', options: ['Isolated Footing','Strip Footing','Raft','Pile','Other'] },
        { key: 'superStructure', label: 'Super Structure', type: 'text' },
        { key: 'roof', label: 'Roof', type: 'select', options: ['RCC Slab','AC Sheet','MS Sheet','Tiled','Terraced','Other'] },
        { key: 'flooring', label: 'Flooring', type: 'select', options: ['Vitrified','Ceramic','Mosaic','Marble','Granite','Earth','Other'] },
        { key: 'doorsWindows', label: 'Doors & Windows', type: 'text' },
        { key: 'electricalFittings', label: 'Electrical Fittings', type: 'select', options: ['Good','Average','Poor','Not Applicable'] },
        { key: 'sanitaryFittings', label: 'Sanitary Fittings', type: 'select', options: ['Good','Average','Poor','Not Applicable'] },
        { key: 'compoundWall', label: 'Compound Wall', type: 'select', options: ['Available','Not Available','Partial'] },
        { key: 'liftAvailable', label: 'Lift Available', type: 'boolean' },
        { key: 'numberOfLifts', label: 'Number of Lifts', type: 'number', showIf: { field: 'liftAvailable', value: true } },
        { key: 'numberOfBlocks', label: 'Number of Blocks', type: 'number' },
        { key: 'numberOfWings', label: 'Number of Wings', type: 'number' },
        { key: 'numberOfUnits', label: 'Number of Units', type: 'number' },
        { key: 'numberOfFloorsApproved', label: 'Number of Floors Approved', type: 'number' },
        { key: 'numberOfFloorsAsBuilt', label: 'Number of Floors As Built', type: 'number' },
        { key: 'floorNumberOfSubject', label: 'Floor Number of Subject Property', type: 'text' },
        { key: 'numberOfRooms', label: 'Number of Rooms', type: 'number', required: true },
        { key: 'constructionQuality', label: 'Construction Quality', type: 'select', options: ['Excellent','Very Good','Good','Average','Poor'] },
        { key: 'constructionStage', label: 'Construction Stage', type: 'select', options: ['Completed','95-100%','75-95%','50-75%','25-50%','Foundation','Plinth','Other'] },
        { key: 'yearOfConstruction', label: 'Year of Construction', type: 'year' },
        { key: 'ageOfProperty', label: 'Age of Property (years)', type: 'number', required: true },
        { key: 'residualLife', label: 'Residual / Future Life (years)', type: 'number', required: true },
        { key: 'internalComposition', label: 'Internal Composition', type: 'textarea' },
      ],
    },
    {
      id: 'floorDetails',
      title: 'Floor-wise Details',
      icon: '🏢',
      type: 'dynamic-table',
      showIf: { field: 'propertyType', notIn: ['Vacant Site','Agricultural'] },
      columns: [
        { key: 'floor', label: 'Floor', type: 'select', options: ['Ground Floor','First Floor','Second Floor','Third Floor','Fourth Floor','Other'] },
        { key: 'carpetArea', label: 'Carpet Area (Sq.Ft)', type: 'number' },
        { key: 'builtUpArea', label: 'Built-up Area (Sq.Ft)', type: 'number' },
        { key: 'grossBuiltUpArea', label: 'Gross BUA (Sq.Ft)', type: 'number' },
        { key: 'superBuiltUpArea', label: 'Super BUA (Sq.Ft)', type: 'number' },
        { key: 'constructionStatus', label: 'Construction Status', type: 'select', options: ['Completed','Under Construction','Not Started'] },
        { key: 'usage', label: 'Usage', type: 'text' },
      ],
    },
    {
      id: 'approvals',
      title: 'Statutory / Approval Details',
      icon: '📑',
      fields: [
        { key: 'buildingApprovalAvailable', label: 'Building Approval Available', type: 'boolean' },
        { key: 'buildingApprovalNumber', label: 'Building Approval Number', type: 'text', showIf: { field: 'buildingApprovalAvailable', value: true } },
        { key: 'buildingApprovalDate', label: 'Building Approval Date', type: 'date', showIf: { field: 'buildingApprovalAvailable', value: true } },
        { key: 'planningApproval', label: 'Planning Approval', type: 'boolean' },
        { key: 'planningApprovalNumber', label: 'Planning Approval Number', type: 'text', showIf: { field: 'planningApproval', value: true } },
        { key: 'dtcpApproval', label: 'DTCP Approval', type: 'select', options: ['Yes','No','N/A'] },
        { key: 'hntdaApproval', label: 'HNTDA Approval', type: 'select', options: ['Yes','No','N/A'] },
        { key: 'rera', label: 'RERA', type: 'select', options: ['Yes','No','N/A'] },
        { key: 'layoutApproval', label: 'Layout Approval', type: 'select', options: ['Yes','No','N/A'] },
        { key: 'sanctionPlanAvailable', label: 'Sanction Plan Available', type: 'boolean' },
        { key: 'sanctionPlanVerified', label: 'Sanction Plan Verified', type: 'boolean' },
        { key: 'constructionAsPerPlan', label: 'Construction As Per Approved Plan', type: 'boolean' },
        { key: 'deviationFromPlan', label: 'Deviation From Approved Plan', type: 'boolean' },
        { key: 'deviationDetails', label: 'Deviation Details', type: 'textarea', showIf: { field: 'deviationFromPlan', value: true } },
        { key: 'ownershipType', label: 'Ownership Type', type: 'select', options: ['Free Hold','Lease Hold','Other'] },
        { key: 'documentsVerified', label: 'Property Documents Verified', type: 'boolean', required: true },
        { key: 'fsrPermitted', label: 'FSI / FAR Permitted', type: 'text' },
        { key: 'fsrActual', label: 'FSI / FAR Actual', type: 'text' },
        { key: 'permissibleBUA', label: 'Permissible Built-up Area', type: 'text' },
        { key: 'actualBUA', label: 'Actual Built-up Area', type: 'text' },
      ],
    },
    {
      id: 'utilities',
      title: 'Utilities & Amenities',
      icon: '⚡',
      fields: [
        { key: 'electricityAvailable', label: 'Electricity Available', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'ebConnection', label: 'EB Connection', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'ebServiceConnectionNo', label: 'EB Service Connection Number', type: 'text' },
        { key: 'waterFacility', label: 'Water Facility', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'undergroundDrainage', label: 'Underground Drainage', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'septicTank', label: 'Septic Tank', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'sump', label: 'Sump', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'overheadTank', label: 'Overhead Tank', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'borewell', label: 'Borewell', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'roadFacility', label: 'Road Facility', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'powerBackup', label: 'Power Backup', type: 'select', options: ['Available','Not Available','Not Applicable'] },
      ],
    },
    {
      id: 'marketRate',
      title: 'Market Rate',
      icon: '💹',
      fields: [
        { key: 'presentMarketRate', label: 'Present Market Rate', type: 'currency' },
        { key: 'averageMarketRate', label: 'Average Market Rate', type: 'currency' },
        { key: 'maxMarketRate', label: 'Maximum Market Rate', type: 'currency' },
        { key: 'minMarketRate', label: 'Minimum Market Rate', type: 'currency' },
        { key: 'guidelineValue', label: 'Guideline Value', type: 'currency' },
        { key: 'rateUnit', label: 'Rate Unit', type: 'select', options: ['Per Sq.Ft','Per Sq.M','Per Cent','Per Acre','Per Ground'] },
        { key: 'propertyClassification', label: 'Property Classification', type: 'text' },
      ],
    },
    {
      id: 'valuation',
      title: 'Valuation',
      icon: '🏦',
      fields: [
        // Land
        { key: 'landArea', label: 'Land / Plot Area', type: 'text' },
        { key: 'landAreaUnit', label: 'Land Area Unit', type: 'select', options: ['Sq.Ft','Sq.M','Cent','Ground','Acre'] },
        { key: 'landRate', label: 'Land Rate', type: 'currency', required: true },
        { key: 'landValue', label: 'Land Value', type: 'calculated', formula: 'landArea × landRate' },
        // UDS
        { key: 'udsAreaVal', label: 'UDS Area', type: 'text' },
        { key: 'udsRate', label: 'UDS Rate', type: 'currency' },
        { key: 'udsValue', label: 'UDS Value', type: 'calculated', formula: 'udsAreaVal × udsRate' },
        // Construction
        { key: 'grossConstructionValue', label: 'Gross Construction Value', type: 'currency' },
        { key: 'depreciationPercent', label: 'Depreciation (%)', type: 'percentage' },
        { key: 'depreciationAmount', label: 'Depreciation Amount', type: 'calculated', formula: 'grossConstructionValue × depreciationPercent / 100' },
        { key: 'netConstructionValue', label: 'Net Construction Value', type: 'calculated', formula: 'grossConstructionValue - depreciationAmount' },
        // Totals
        { key: 'amenitiesValue', label: 'Amenities Value', type: 'currency' },
        { key: 'otherValue', label: 'Other Value', type: 'currency' },
        { key: 'totalPropertyValue', label: 'TOTAL PROPERTY VALUE', type: 'calculated', formula: 'landValue + netConstructionValue + amenitiesValue + otherValue' },
        { key: 'presentMarketValue', label: 'Present Market Value', type: 'calculated', formula: 'totalPropertyValue' },
        { key: 'realizableValue', label: 'Realizable Value (90%)', type: 'calculated', formula: 'totalPropertyValue × 0.9' },
        { key: 'forcedSaleValue', label: 'Forced Sale Value (75%)', type: 'calculated', formula: 'totalPropertyValue × 0.75' },
        { key: 'recommendedValue', label: 'Recommended Value', type: 'currency' },
        { key: 'valueInWords', label: 'Value In Words', type: 'text', readonly: true },
      ],
    },
    {
      id: 'riskFlags',
      title: 'Risk Flags',
      icon: '⚠️',
      fields: [
        { key: 'negativeAreaFlag', label: 'Property In Negative Area', type: 'boolean' },
        { key: 'inOGL', label: 'Property In OGL', type: 'boolean' },
        { key: 'riskOfDemolition', label: 'Risk of Demolition', type: 'select', options: ['Nil','Low','Medium','High'] },
        { key: 'legalConcern', label: 'Legal Concern', type: 'boolean' },
        { key: 'documentConcern', label: 'Document Concern', type: 'boolean' },
        { key: 'boundaryConcern', label: 'Boundary Concern', type: 'boolean' },
        { key: 'approvalConcern', label: 'Approval Concern', type: 'boolean' },
        { key: 'deviationConcern', label: 'Deviation Concern', type: 'boolean' },
        { key: 'environmentalRisk', label: 'Environmental Risk', type: 'boolean' },
        { key: 'riskRemarks', label: 'Risk Remarks', type: 'textarea' },
      ],
    },
    {
      id: 'remarks',
      title: 'Remarks & Observations',
      icon: '📝',
      fields: [
        { key: 'propertyRemarks', label: 'Property Remarks', type: 'textarea' },
        { key: 'documentRemarks', label: 'Document Remarks', type: 'textarea' },
        { key: 'legalRemarks', label: 'Legal Remarks', type: 'textarea' },
        { key: 'technicalRemarks', label: 'Technical Remarks', type: 'textarea' },
        { key: 'valuationRemarks', label: 'Valuation Remarks', type: 'textarea' },
        { key: 'boundaryRemarks', label: 'Boundary Remarks', type: 'textarea' },
        { key: 'approvalRemarks', label: 'Approval Remarks', type: 'textarea' },
        { key: 'valuerRemarks', label: 'Valuer Remarks / Observation', type: 'textarea', required: true },
        { key: 'otherRemarks', label: 'Other Remarks', type: 'textarea' },
      ],
    },
    {
      id: 'recommendation',
      title: 'Recommendation',
      icon: '✅',
      fields: [
        { key: 'presentStatusOfWork', label: 'Present Status Of Work', type: 'textarea' },
        { key: 'valuerRecommendation', label: 'Valuer Recommendation', type: 'textarea', required: true },
        { key: 'finalRecommendation', label: 'Final Recommendation', type: 'select', options: ['Recommended','Not Recommended','Conditionally Recommended'] },
        { key: 'documentsVerifiedFinal', label: 'Documents Verified', type: 'boolean' },
        { key: 'pattaVerified', label: 'Patta Verified', type: 'boolean' },
        { key: 'fmbVerified', label: 'FMB Verified', type: 'boolean' },
        { key: 'ebDetailsVerified', label: 'EB Details Verified', type: 'boolean' },
        { key: 'onlineLandRecordsVerified', label: 'Online Land Records Verified', type: 'boolean' },
      ],
    },
  ],

  // Photo categories — which ones are mandatory
  photoCategories: [
    { key: 'frontView', label: 'Front View', mandatory: true },
    { key: 'roadAccess', label: 'Road Access', mandatory: true },
    { key: 'northBoundary', label: 'North Boundary', mandatory: true },
    { key: 'southBoundary', label: 'South Boundary', mandatory: true },
    { key: 'eastBoundary', label: 'East Boundary', mandatory: true },
    { key: 'westBoundary', label: 'West Boundary', mandatory: true },
    { key: 'propertyOverall', label: 'Property Overall', mandatory: false },
    { key: 'buildingExterior', label: 'Building Exterior', mandatory: false },
    { key: 'buildingInterior', label: 'Building Interior', mandatory: false },
    { key: 'surrounding', label: 'Surrounding Area', mandatory: false },
    { key: 'landmark', label: 'Landmark', mandatory: false },
    { key: 'documentPhotos', label: 'Document Photos', mandatory: false },
    { key: 'other', label: 'Other', mandatory: false },
  ],

  // Document types
  documentCategories: [
    'Sale Deed','Partition Deed','Patta','FMB Sketch','EC','EB Details',
    'Property Tax','Building Approval','Building Plan','Layout Approval',
    'DTCP Approval','HNTDA Approval','RERA','Construction Permission',
    'TNGIS','Online Land Record','Other',
  ],

  // Bank-specific declaration text
  declarationText: 'I/We hereby declare that the above valuation report has been prepared by me/us in my/our professional capacity and that the said valuation is fair and correct to the best of my/our knowledge and belief. I/We have no interest/concern, financially or otherwise, in the property. I/We have personally visited and inspected the subject property. The property has been valued in accordance with the instructions given by Ujjivan Small Finance Bank. The total value stated herein is my/our opinion of the present market value of the above described property.',

  // Step wizard sequence
  steps: [
    'caseInfo','applicant','propertyIdentification','addressDocument','addressSite',
    'locationAccess','locality','plotSite','boundaries','occupancy',
    'building','floorDetails','approvals','utilities','marketRate',
    'valuation','riskFlags','remarks','recommendation',
    'documents','photos','gps','declaration','review',
  ],
}

// ─── NIVARA TEMPLATE V1 ───
export const NIVARA_TEMPLATE_V1 = {
  bank: 'NIVARA',
  bankName: 'Nivara Housing Finance Ltd.',
  templateId: 'nivara-technical-v1',
  templateName: 'Nivara Technical Appraisal V1',
  version: 1,
  reportFormat: 'xlsx',

  sections: [
    // All Ujjivan sections are inherited, then extras are added
    // ─── Extra Nivara Case Fields ───
    {
      id: 'caseInfo',
      title: 'Case Information',
      icon: '📋',
      fields: [
        { key: 'refNo', label: 'Reference Number', type: 'text', required: true },
        { key: 'nivaraRefNo', label: 'Nivara Reference Number', type: 'text' },
        { key: 'reportDate', label: 'Report Date', type: 'date', required: true },
        { key: 'dateOfInspection', label: 'Date of Inspection', type: 'date', required: true },
        { key: 'caseType', label: 'Type of Case', type: 'select', options: ['Housing Loan','LAP','Resale','NRP','Others'], required: true },
        { key: 'purposeOfValuation', label: 'Purpose of Valuation', type: 'select', options: ['Housing Loan','Resale Purchase','OD','Others'], required: true },
        { key: 'valuerName', label: 'Valuer Name', type: 'text', required: true },
        { key: 'valuerContact', label: 'Valuer Contact Number', type: 'phone' },
        { key: 'branchName', label: 'Branch', type: 'text', required: true },
        { key: 'contactedPerson', label: 'Person Contacted During Inspection', type: 'text', required: true },
        { key: 'contactPersonMobile', label: 'Contact Person Mobile', type: 'phone' },
        { key: 'previousValuationDone', label: 'Previous Valuation Done', type: 'boolean' },
        { key: 'previousValuationDate', label: 'Previous Valuation Date', type: 'date', showIf: { field: 'previousValuationDone', value: true } },
        { key: 'previousValuationForWhom', label: 'Previous Valuation For Whom', type: 'text', showIf: { field: 'previousValuationDone', value: true } },
        { key: 'nearestLandmark', label: 'Nearest Landmark', type: 'text' },
        { key: 'distanceFromCity', label: 'Distance From City Centre', type: 'text' },
      ],
    },
    {
      id: 'applicant',
      title: 'Applicant Details',
      icon: '👤',
      fields: [
        { key: 'applicantName', label: 'Applicant Name', type: 'text', required: true },
        { key: 'coApplicantName', label: 'Co-Applicant Name', type: 'text' },
        { key: 'customerId', label: 'Customer ID', type: 'text' },
        { key: 'clientId', label: 'Client ID', type: 'text' },
        { key: 'applicantContact', label: 'Applicant Contact Number', type: 'phone' },
        { key: 'ownerName', label: 'Owner Name', type: 'text', required: true },
        { key: 'propertyOwnerName', label: 'Property Owner Name', type: 'text' },
        { key: 'ownerContact', label: 'Owner Contact Number', type: 'phone' },
        { key: 'relationshipWithApplicant', label: 'Relationship With Applicant', type: 'select', options: ['Self','Applicant','Spouse','Parent','Sibling','Other'] },
        { key: 'previousValuationDetails', label: 'Previous Valuation Details', type: 'textarea' },
      ],
    },
    // Property, address, location, locality, plot — same as Ujjivan
    {
      id: 'propertyIdentification',
      title: 'Property Identification',
      icon: '🏠',
      fields: [
        { key: 'propertyType', label: 'Property Type', type: 'select', required: true, options: ['Vacant Site','Residential','Commercial','Industrial','Apartment','Villa','Agricultural','Mixed Use','Other'] },
        { key: 'propertySubType', label: 'Property Sub-Type', type: 'text' },
        { key: 'currentUsage', label: 'Current Usage', type: 'text', required: true },
        { key: 'permittedUsage', label: 'Permitted Usage', type: 'text' },
        { key: 'surveyNumber', label: 'Survey Number', type: 'text', required: true },
        { key: 'oldSurveyNumber', label: 'Old Survey Number', type: 'text' },
        { key: 'newSurveyNumber', label: 'New Survey Number', type: 'text' },
        { key: 'subDivisionNumber', label: 'Survey / Sub-Division Number', type: 'text' },
        { key: 'plotNumber', label: 'Plot Number', type: 'text' },
        { key: 'doorNumber', label: 'Door Number', type: 'text' },
        { key: 'village', label: 'Village', type: 'text' },
        { key: 'panchayat', label: 'Panchayat', type: 'text' },
        { key: 'taluk', label: 'Taluk', type: 'text', required: true },
        { key: 'district', label: 'District', type: 'text', required: true },
        { key: 'state', label: 'State', type: 'text', required: true },
        { key: 'pincode', label: 'Pincode', type: 'text' },
        { key: 'propertyIdentified', label: 'Property Identified', type: 'boolean', required: true },
      ],
    },
    {
      id: 'addressDocument',
      title: 'Address As Per Document',
      icon: '📄',
      fields: [
        { key: 'docAddrDoorNo', label: 'Door / Plot Number', type: 'text' },
        { key: 'docAddrSurveyNo', label: 'Survey Number', type: 'text' },
        { key: 'docAddrStreet', label: 'Street', type: 'text' },
        { key: 'docAddrVillage', label: 'Village', type: 'text' },
        { key: 'docAddrTaluk', label: 'Taluk', type: 'text' },
        { key: 'docAddrDistrict', label: 'District', type: 'text' },
        { key: 'docAddrState', label: 'State', type: 'text' },
        { key: 'docAddrPincode', label: 'Pincode', type: 'text' },
        { key: 'documentAddress', label: 'Full Document Address', type: 'textarea' },
      ],
    },
    {
      id: 'addressSite',
      title: 'Address As At Site',
      icon: '📍',
      fields: [
        { key: 'siteAddrSameAsDoc', label: 'Address Same As Document', type: 'boolean' },
        { key: 'siteAddrDoorNo', label: 'Door / Plot Number', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddrSurveyNo', label: 'Survey Number', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddrStreet', label: 'Street', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddrVillage', label: 'Village', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddrTaluk', label: 'Taluk', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddrDistrict', label: 'District', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddrPincode', label: 'Pincode', type: 'text', showIf: { field: 'siteAddrSameAsDoc', value: false } },
        { key: 'siteAddress', label: 'Full Site Address', type: 'textarea', required: true },
      ],
    },
    {
      id: 'locationAccess',
      title: 'Location & Access',
      icon: '🛣️',
      fields: [
        { key: 'accessRoadType', label: 'Access Road Type', type: 'select', options: ['National Highway','State Highway','District Road','Panchayat Road','Private Road','Other'] },
        { key: 'approachRoadCondition', label: 'Approach Road Condition', type: 'select', options: ['Good','Average','Poor'] },
        { key: 'approachRoadWidth', label: 'Approach Road Width', type: 'text' },
        { key: 'distanceFromBranch', label: 'Distance From Branch (km)', type: 'text', required: true },
        { key: 'nearestLandmark', label: 'Nearest Landmark', type: 'text' },
        { key: 'publicTransport', label: 'Public Transport Availability', type: 'select', options: ['Available','Limited','Not Available'] },
        { key: 'surroundingLocality', label: 'Surrounding Locality', type: 'textarea' },
      ],
    },
    {
      id: 'plotSite',
      title: 'Plot / Site Details',
      icon: '📐',
      fields: [
        { key: 'plotShape', label: 'Plot Shape', type: 'select', options: ['Regular','Irregular','Square','Rectangular','Triangular','L-Shape','Other'] },
        { key: 'siteAreaDoc', label: 'Site Area As Per Document', type: 'text' },
        { key: 'siteAreaPatta', label: 'Site Area As Per Patta', type: 'text' },
        { key: 'siteAreaActual', label: 'Site Area As At Site (Actual)', type: 'text', required: true },
        { key: 'plotArea', label: 'Plot Area', type: 'text', required: true },
        { key: 'udsArea', label: 'UDS Area', type: 'text' },
        { key: 'areaUnit', label: 'Area Unit', type: 'select', options: ['Sq.Ft','Sq.M','Sq.Yard','Acre','Cent','Ground','Other'] },
        { key: 'areaForValuation', label: 'Area Considered For Valuation', type: 'text', required: true },
        { key: 'northDimension', label: 'North Dimension', type: 'text' },
        { key: 'southDimension', label: 'South Dimension', type: 'text' },
        { key: 'eastDimension', label: 'East Dimension', type: 'text' },
        { key: 'westDimension', label: 'West Dimension', type: 'text' },
      ],
    },
    {
      id: 'boundaries',
      title: 'Boundary Details',
      icon: '🧭',
      fields: [
        { key: 'northBoundaryDoc', label: 'North — As Per Document', type: 'text', required: true },
        { key: 'northBoundarySite', label: 'North — As At Site', type: 'text', required: true },
        { key: 'southBoundaryDoc', label: 'South — As Per Document', type: 'text', required: true },
        { key: 'southBoundarySite', label: 'South — As At Site', type: 'text', required: true },
        { key: 'eastBoundaryDoc', label: 'East — As Per Document', type: 'text', required: true },
        { key: 'eastBoundarySite', label: 'East — As At Site', type: 'text', required: true },
        { key: 'westBoundaryDoc', label: 'West — As Per Document', type: 'text', required: true },
        { key: 'westBoundarySite', label: 'West — As At Site', type: 'text', required: true },
        { key: 'boundariesMatching', label: 'Boundaries Matching', type: 'boolean', required: true },
        { key: 'boundaryDifferenceRemarks', label: 'Boundary Difference Remarks', type: 'textarea', showIf: { field: 'boundariesMatching', value: false } },
      ],
    },
    {
      id: 'occupancy',
      title: 'Occupancy',
      icon: '🔑',
      fields: [
        { key: 'presentOccupancy', label: 'Present Occupancy', type: 'select', required: true, options: ['Self Occupied','Tenant Occupied','Vacant','Partially Occupied','Under Construction','Other'] },
        { key: 'occupantName', label: 'Occupant Name', type: 'text' },
        { key: 'occupantRelationship', label: 'Relationship With Applicant', type: 'select', options: ['Self','Applicant','Spouse','Parent','Sibling','Tenant','Other'] },
        { key: 'usageVerified', label: 'Usage Verified', type: 'boolean' },
      ],
    },
    {
      id: 'building',
      title: 'Building / Structure Details',
      icon: '🏗️',
      showIf: { field: 'propertyType', notIn: ['Vacant Site','Agricultural'] },
      fields: [
        { key: 'typeOfStructure', label: 'Type of Structure', type: 'select', options: ['RCC','Load Bearing','Steel','Timber','Brick','Other'] },
        { key: 'typeOfConstruction', label: 'Type of Construction', type: 'select', options: ['Framed','Load Bearing','Composite','Other'] },
        { key: 'foundation', label: 'Foundation', type: 'text' },
        { key: 'superStructure', label: 'Super Structure', type: 'text' },
        { key: 'roof', label: 'Roof', type: 'select', options: ['RCC Slab','AC Sheet','MS Sheet','Tiled','Terraced','Other'] },
        { key: 'flooring', label: 'Flooring', type: 'text' },
        { key: 'electricalFittings', label: 'Electrical Fittings', type: 'select', options: ['Good','Average','Poor','Not Applicable'] },
        { key: 'sanitaryFittings', label: 'Sanitary Fittings', type: 'select', options: ['Good','Average','Poor','Not Applicable'] },
        { key: 'numberOfFloorsApproved', label: 'Number of Floors Approved', type: 'number' },
        { key: 'numberOfFloorsAsBuilt', label: 'Number of Floors As Built', type: 'number' },
        { key: 'numberOfRooms', label: 'Number of Rooms', type: 'number', required: true },
        { key: 'constructionQuality', label: 'Construction Quality', type: 'select', options: ['Excellent','Very Good','Good','Average','Poor'] },
        { key: 'constructionStage', label: 'Construction Stage', type: 'select', options: ['Completed','95-100%','75-95%','50-75%','25-50%','Foundation','Plinth','Other'] },
        { key: 'ageOfProperty', label: 'Age of Property (years)', type: 'number', required: true },
        { key: 'residualLife', label: 'Residual Life (years)', type: 'number', required: true },
      ],
    },
    {
      id: 'setback',
      title: 'Setback Details',
      icon: '📏',
      type: 'dynamic-table',
      bankSpecific: true,
      columns: [
        { key: 'side', label: 'Setback Side', type: 'select', options: ['Front','Rear','Right Side','Left Side'] },
        { key: 'asPlan', label: 'As Per Plan / Bye-Laws', type: 'text' },
        { key: 'actual', label: 'Actual At Site', type: 'text' },
        { key: 'floor', label: 'Floor', type: 'text' },
        { key: 'deviation', label: 'Deviation', type: 'text' },
        { key: 'remarks', label: 'Remarks', type: 'text' },
      ],
      additionalFields: [
        { key: 'setbackCompliance', label: 'Setback Compliance', type: 'select', options: ['Yes','No','Partial'] },
        { key: 'riskOfDemolition', label: 'Risk of Demolition', type: 'select', options: ['Nil','Low','Medium','High'] },
      ],
    },
    {
      id: 'floorDetails',
      title: 'Floor-wise Details',
      icon: '🏢',
      type: 'dynamic-table',
      showIf: { field: 'propertyType', notIn: ['Vacant Site','Agricultural'] },
      columns: [
        { key: 'floor', label: 'Floor', type: 'select', options: ['Ground Floor','First Floor','Second Floor','Third Floor','Other'] },
        { key: 'carpetArea', label: 'Carpet Area (Sq.Ft)', type: 'number' },
        { key: 'builtUpArea', label: 'Built-up Area (Sq.Ft)', type: 'number' },
        { key: 'superBuiltUpArea', label: 'Super BUA (Sq.Ft)', type: 'number' },
        { key: 'constructionStatus', label: 'Construction Status', type: 'select', options: ['Completed','Under Construction'] },
        { key: 'usage', label: 'Usage', type: 'text' },
      ],
    },
    {
      id: 'approvals',
      title: 'Statutory / Approval Details',
      icon: '📑',
      fields: [
        { key: 'buildingApprovalAvailable', label: 'Building Approval Available', type: 'boolean' },
        { key: 'buildingApprovalNumber', label: 'Building Approval Number', type: 'text', showIf: { field: 'buildingApprovalAvailable', value: true } },
        { key: 'buildingApprovalDate', label: 'Building Approval Date', type: 'date', showIf: { field: 'buildingApprovalAvailable', value: true } },
        { key: 'dtcpApproval', label: 'DTCP Approval', type: 'select', options: ['Yes','No','N/A'] },
        { key: 'rera', label: 'RERA', type: 'select', options: ['Yes','No','N/A'] },
        { key: 'sanctionPlanAvailable', label: 'Sanction Plan Available', type: 'boolean' },
        { key: 'constructionAsPerPlan', label: 'Construction As Per Approved Plan', type: 'boolean' },
        { key: 'deviationFromPlan', label: 'Deviation From Approved Plan', type: 'boolean' },
        { key: 'deviationDetails', label: 'Deviation Details', type: 'textarea', showIf: { field: 'deviationFromPlan', value: true } },
        { key: 'ownershipType', label: 'Ownership Type', type: 'select', options: ['Free Hold','Lease Hold','Other'] },
        { key: 'documentsVerified', label: 'Property Documents Verified', type: 'boolean', required: true },
        { key: 'fsrPermitted', label: 'FSI / FAR Permitted', type: 'text' },
        { key: 'fsrActual', label: 'FSI / FAR Actual', type: 'text' },
        { key: 'nbcCompliance', label: 'NBC Compliance', type: 'select', options: ['Yes','No','N/A'] },
        { key: 'ndmaCompliance', label: 'NDMA Compliance', type: 'select', options: ['Yes','No','N/A'] },
        { key: 'complianceRemarks', label: 'Compliance Remarks', type: 'textarea' },
      ],
    },
    {
      id: 'environmental',
      title: 'Environmental / NDMA Parameters',
      icon: '🌍',
      bankSpecific: true,
      fields: [
        { key: 'floodRisk', label: 'Flood Risk', type: 'boolean' },
        { key: 'floodZone', label: 'Flood Zone', type: 'text', showIf: { field: 'floodRisk', value: true } },
        { key: 'floodRemarks', label: 'Flood Remarks', type: 'textarea' },
        { key: 'seismicZone', label: 'Seismic Zone', type: 'select', options: ['Zone I','Zone II','Zone III','Zone IV','Zone V'] },
        { key: 'seismicRisk', label: 'Seismic Risk', type: 'select', options: ['Low','Moderate','High','Very High'] },
        { key: 'cycloneProne', label: 'Cyclone Prone', type: 'boolean' },
        { key: 'cycloneZone', label: 'Cyclone Zone', type: 'text' },
        { key: 'landslideRisk', label: 'Landslide Risk', type: 'boolean' },
        { key: 'coastalRegulationZone', label: 'Coastal Regulation Zone', type: 'boolean' },
        { key: 'crzCategory', label: 'CRZ Category', type: 'text', showIf: { field: 'coastalRegulationZone', value: true } },
        { key: 'soilType', label: 'Soil Type', type: 'select', options: ['Black Cotton','Red Soil','Sandy','Clay','Loamy','Rocky','Other'] },
        { key: 'soilCondition', label: 'Soil Condition', type: 'select', options: ['Good','Average','Poor'] },
        { key: 'environmentalExposure', label: 'Environmental Exposure Condition', type: 'textarea' },
        { key: 'pollutionExposure', label: 'Pollution Exposure', type: 'select', options: ['Nil','Low','Moderate','High'] },
        { key: 'industrialExposure', label: 'Industrial Exposure', type: 'select', options: ['Nil','Low','Moderate','High'] },
      ],
    },
    {
      id: 'onlineLandRecord',
      title: 'Online Land Revenue Records',
      icon: '💻',
      bankSpecific: true,
      fields: [
        { key: 'onlineRecordAvailable', label: 'Online Record Available', type: 'boolean' },
        { key: 'natureLandOnline', label: 'Nature of Land As Per Online Record', type: 'text' },
        { key: 'ownershipOnline', label: 'Ownership As Per Online Record', type: 'text' },
        { key: 'areaOnline', label: 'Area As Per Online Record', type: 'text' },
        { key: 'surveyNoOnline', label: 'Survey Number As Per Online Record', type: 'text' },
        { key: 'onlineRecordVerification', label: 'Record Verification Status', type: 'select', options: ['Verified','Not Verified','Not Available'] },
        { key: 'onlineRecordRemarks', label: 'Online Record Remarks', type: 'textarea' },
      ],
    },
    {
      id: 'amenitiesTable',
      title: 'Extra Amenities (Nivara)',
      icon: '🏊',
      type: 'dynamic-table',
      bankSpecific: true,
      columns: [
        { key: 'amenity', label: 'Amenity', type: 'select', options: ['Car Parking','Sump','OHT','Septic Tank','EB Arrangement','Borewell','PLC','IDC','EDC','Power Backup','Other'] },
        { key: 'quantity', label: 'Quantity', type: 'number' },
        { key: 'rate', label: 'Rate (Rs.)', type: 'currency' },
        { key: 'amount', label: 'Amount (Auto)', type: 'calculated', formula: 'quantity × rate' },
      ],
    },
    {
      id: 'utilities',
      title: 'Utilities',
      icon: '⚡',
      fields: [
        { key: 'electricityAvailable', label: 'Electricity', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'waterFacility', label: 'Water Facility', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'undergroundDrainage', label: 'Underground Drainage', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'sump', label: 'Sump', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'borewell', label: 'Borewell', type: 'select', options: ['Available','Not Available','Not Applicable'] },
        { key: 'roadFacility', label: 'Road Facility', type: 'select', options: ['Available','Not Available','Not Applicable'] },
      ],
    },
    {
      id: 'marketRate',
      title: 'Market Rate',
      icon: '💹',
      fields: [
        { key: 'presentMarketRate', label: 'Present Market Rate', type: 'currency' },
        { key: 'averageMarketRate', label: 'Average Market Rate', type: 'currency' },
        { key: 'guidelineValue', label: 'Guideline Value', type: 'currency' },
        { key: 'guidelineValuePerAcre', label: 'Guideline Value Per Acre', type: 'currency' },
        { key: 'rateUnit', label: 'Rate Unit', type: 'select', options: ['Per Sq.Ft','Per Sq.M','Per Cent','Per Acre','Per Ground'] },
        { key: 'propertyClassification', label: 'Property Classification', type: 'text' },
      ],
    },
    {
      id: 'valuation',
      title: 'Valuation',
      icon: '🏦',
      fields: [
        { key: 'landArea', label: 'Land / Plot Area', type: 'text' },
        { key: 'landAreaUnit', label: 'Land Area Unit', type: 'select', options: ['Sq.Ft','Sq.M','Cent','Ground','Acre'] },
        { key: 'landRate', label: 'Land Rate (Rs.)', type: 'currency', required: true },
        { key: 'landValue', label: 'Land Value (Auto)', type: 'calculated', formula: 'landArea × landRate' },
        { key: 'udsAreaVal', label: 'UDS Area', type: 'text' },
        { key: 'udsRate', label: 'UDS Rate', type: 'currency' },
        { key: 'udsValue', label: 'UDS Value (Auto)', type: 'calculated', formula: 'udsAreaVal × udsRate' },
        { key: 'grossConstructionValue', label: 'Gross Construction Value', type: 'currency' },
        { key: 'depreciationPercent', label: 'Depreciation (%)', type: 'percentage' },
        { key: 'depreciationAmount', label: 'Depreciation Amount (Auto)', type: 'calculated', formula: 'grossConstructionValue × depreciationPercent / 100' },
        { key: 'netConstructionValue', label: 'Net Construction Value (Auto)', type: 'calculated', formula: 'grossConstructionValue - depreciationAmount' },
        { key: 'amenitiesValueTotal', label: 'Total Amenities Value (Auto)', type: 'calculated', formula: 'SUM(amenitiesTable.amount)' },
        { key: 'totalPropertyValue', label: 'TOTAL PROPERTY VALUE (Auto)', type: 'calculated', formula: 'landValue + netConstructionValue + amenitiesValueTotal' },
        { key: 'presentMarketValue', label: 'Present Market Value', type: 'calculated', formula: 'totalPropertyValue' },
        { key: 'realizableValue', label: 'Realizable Value (90%)', type: 'calculated', formula: 'totalPropertyValue × 0.9' },
        { key: 'forcedSaleValue', label: 'Forced Sale Value (75%)', type: 'calculated', formula: 'totalPropertyValue × 0.75' },
        { key: 'estimatedMonthlyRent', label: 'Estimated Monthly Rent (100% Completion)', type: 'currency' },
        { key: 'estimatedMonthlyRentCurrent', label: 'Estimated Monthly Rent (Current Stage)', type: 'currency' },
        { key: 'rentalRemarks', label: 'Rental Remarks', type: 'textarea' },
        { key: 'valueInWords', label: 'Value In Words', type: 'text', readonly: true },
      ],
    },
    {
      id: 'riskFlags',
      title: 'Risk Flags',
      icon: '⚠️',
      fields: [
        { key: 'negativeAreaFlag', label: 'Property In Negative Area', type: 'boolean' },
        { key: 'inOGL', label: 'Property In OGL', type: 'boolean' },
        { key: 'riskOfDemolition', label: 'Risk of Demolition', type: 'select', options: ['Nil','Low','Medium','High'] },
        { key: 'legalConcern', label: 'Legal Concern', type: 'boolean' },
        { key: 'documentConcern', label: 'Document Concern', type: 'boolean' },
        { key: 'boundaryConcern', label: 'Boundary Concern', type: 'boolean' },
        { key: 'approvalConcern', label: 'Approval Concern', type: 'boolean' },
        { key: 'environmentalRisk', label: 'Environmental Risk', type: 'boolean' },
        { key: 'riskRemarks', label: 'Risk Remarks', type: 'textarea' },
      ],
    },
    {
      id: 'remarks',
      title: 'Remarks & Observations',
      icon: '📝',
      fields: [
        { key: 'propertyRemarks', label: 'Property Remarks', type: 'textarea' },
        { key: 'documentRemarks', label: 'Document Remarks', type: 'textarea' },
        { key: 'technicalRemarks', label: 'Technical Remarks', type: 'textarea' },
        { key: 'valuationRemarks', label: 'Valuation Remarks', type: 'textarea' },
        { key: 'boundaryRemarks', label: 'Boundary Remarks', type: 'textarea' },
        { key: 'approvalRemarks', label: 'Approval Remarks', type: 'textarea' },
        { key: 'environmentalRemarks', label: 'Environmental Remarks', type: 'textarea' },
        { key: 'valuerRemarks', label: 'Valuer Remarks / Observation', type: 'textarea', required: true },
      ],
    },
    {
      id: 'recommendation',
      title: 'Recommendation',
      icon: '✅',
      fields: [
        { key: 'valuerRecommendation', label: 'Valuer Recommendation', type: 'textarea', required: true },
        { key: 'finalRecommendation', label: 'Final Recommendation', type: 'select', options: ['Recommended','Not Recommended','Conditionally Recommended'] },
        { key: 'documentsVerifiedFinal', label: 'Documents Verified', type: 'boolean' },
        { key: 'pattaVerified', label: 'Patta Verified', type: 'boolean' },
        { key: 'fmbVerified', label: 'FMB Verified', type: 'boolean' },
        { key: 'onlineLandRecordsVerified', label: 'Online Land Records Verified', type: 'boolean' },
        { key: 'tngisVerified', label: 'TNGIS Verified', type: 'boolean' },
      ],
    },
  ],

  photoCategories: [
    { key: 'frontView', label: 'Front View', mandatory: true },
    { key: 'roadAccess', label: 'Road Access', mandatory: true },
    { key: 'northBoundary', label: 'North Boundary', mandatory: true },
    { key: 'southBoundary', label: 'South Boundary', mandatory: true },
    { key: 'eastBoundary', label: 'East Boundary', mandatory: true },
    { key: 'westBoundary', label: 'West Boundary', mandatory: true },
    { key: 'buildingExterior', label: 'Building Exterior', mandatory: true },
    { key: 'buildingInterior', label: 'Building Interior', mandatory: false },
    { key: 'surrounding', label: 'Surrounding Area', mandatory: false },
    { key: 'landmark', label: 'Landmark', mandatory: false },
    { key: 'documentPhotos', label: 'Document Photos', mandatory: false },
    { key: 'other', label: 'Other', mandatory: false },
  ],

  documentCategories: [
    'Sale Deed','Partition Deed','Patta','FMB Sketch','EC','EB Details',
    'Property Tax','Building Approval','Building Plan','Layout Approval',
    'DTCP Approval','RERA','Construction Permission','TNGIS','Online Land Record','Other',
  ],

  declarationText: 'I/We hereby certify that I/We have personally inspected the property described herein and the same has been valued at its market value as on the date of inspection, as per the instructions of Nivara Housing Finance Ltd. The valuation is based on the documents produced and the information furnished, which I/We believe to be correct. I/We declare that I/We have no interest/concern, directly or indirectly, in the property valued and no conflict of interest exist.',

  steps: [
    'caseInfo','applicant','propertyIdentification','addressDocument','addressSite',
    'locationAccess','plotSite','boundaries','occupancy','building','setback',
    'floorDetails','approvals','environmental','onlineLandRecord','amenitiesTable',
    'utilities','marketRate','valuation','riskFlags','remarks','recommendation',
    'documents','photos','gps','declaration','review',
  ],
}

export const BANK_TEMPLATES = {
  UJJ: UJJIVAN_TEMPLATE_V1,
  NIVARA: NIVARA_TEMPLATE_V1,
}

export function getTemplate(bankCode) {
  return BANK_TEMPLATES[String(bankCode || '').toUpperCase()] || null
}
